language:
    - C
services:
    - docker
script:
    - echo "32-bit..."
    - docker run --rm -i -v ${PWD}:/unixODBC -eBUILD_WIDTH=32 tubia/debian:wheezy /unixODBC/dbuild.sh
    - echo "64-bit..."
    - docker run --rm -i -v ${PWD}:/unixODBC -eBUILD_WIDTH=64 debian:wheezy /unixODBC/dbuild.sh
